# Generated by Django 3.2.25 on 2026-04-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_myphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
